CREATE TABLE ipv4_city_blocks_0(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_1(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_2(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_3(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_4(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_5(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_6(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_7(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_8(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_9(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_10(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_11(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_12(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_13(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_14(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_15(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_16(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_17(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_18(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_19(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_20(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_21(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_22(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_23(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_24(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_25(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_26(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_27(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_28(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_29(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_30(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_31(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_32(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_33(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_34(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_35(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_36(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_37(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_38(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);
CREATE TABLE ipv4_city_blocks_39(network_start_integer INTEGER,network_last_integer INTEGER,geoname_id INTEGER,registered_country_geoname_id INTEGER,represented_country_geoname_id INTEGER,is_anonymous_proxy INTEGER,is_satellite_provider INTEGER,postal_code INTEGER,latitude REAL,longitude REAL);

INSERT INTO ipv4_city_blocks_0 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_0 );
INSERT INTO ipv4_city_blocks_1 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_1 );
INSERT INTO ipv4_city_blocks_2 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_2 );
INSERT INTO ipv4_city_blocks_3 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_3 );
INSERT INTO ipv4_city_blocks_4 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_4 );
INSERT INTO ipv4_city_blocks_5 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_5 );
INSERT INTO ipv4_city_blocks_6 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_6 );
INSERT INTO ipv4_city_blocks_7 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_7 );
INSERT INTO ipv4_city_blocks_8 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_8 );
INSERT INTO ipv4_city_blocks_9 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_9 );
INSERT INTO ipv4_city_blocks_10 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_10 );
INSERT INTO ipv4_city_blocks_11 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_11 );
INSERT INTO ipv4_city_blocks_12 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_12 );
INSERT INTO ipv4_city_blocks_13 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_13 );
INSERT INTO ipv4_city_blocks_14 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_14 );
INSERT INTO ipv4_city_blocks_15 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_15 );
INSERT INTO ipv4_city_blocks_16 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_16 );
INSERT INTO ipv4_city_blocks_17 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_17 );
INSERT INTO ipv4_city_blocks_18 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_18 );
INSERT INTO ipv4_city_blocks_19 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_19 );
INSERT INTO ipv4_city_blocks_20 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_20 );
INSERT INTO ipv4_city_blocks_21 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_21 );
INSERT INTO ipv4_city_blocks_22 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_22 );
INSERT INTO ipv4_city_blocks_23 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_23 );
INSERT INTO ipv4_city_blocks_24 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_24 );
INSERT INTO ipv4_city_blocks_25 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_25 );
INSERT INTO ipv4_city_blocks_26 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_26 );
INSERT INTO ipv4_city_blocks_27 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_27 );
INSERT INTO ipv4_city_blocks_28 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_28 );
INSERT INTO ipv4_city_blocks_29 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_29 );
INSERT INTO ipv4_city_blocks_30 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_30 );
INSERT INTO ipv4_city_blocks_31 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_31 );
INSERT INTO ipv4_city_blocks_32 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_32 );
INSERT INTO ipv4_city_blocks_33 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_33 );
INSERT INTO ipv4_city_blocks_34 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_34 );
INSERT INTO ipv4_city_blocks_35 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_35 );
INSERT INTO ipv4_city_blocks_36 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_36 );
INSERT INTO ipv4_city_blocks_37 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_37 );
INSERT INTO ipv4_city_blocks_38 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer LIMIT 76000;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_38 );
INSERT INTO ipv4_city_blocks_39 SELECT * FROM ipv4_city_blocks ORDER BY network_start_integer;
DELETE FROM ipv4_city_blocks WHERE network_start_integer IN ( SELECT network_start_integer FROM ipv4_city_blocks_39 );

DROP TABLE ipv4_city_blocks;

CREATE TABLE ipv4_ranges(table_name TEXT, min INTEGER, max INTEGER);

INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_0", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_0;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_1", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_1;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_2", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_2;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_3", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_3;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_4", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_4;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_5", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_5;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_6", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_6;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_7", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_7;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_8", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_8;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_9", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_9;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_10", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_10;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_11", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_11;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_12", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_12;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_13", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_13;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_14", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_14;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_15", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_15;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_16", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_16;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_17", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_17;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_18", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_18;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_19", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_19;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_20", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_20;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_21", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_21;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_22", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_22;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_23", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_23;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_24", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_24;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_25", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_25;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_26", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_26;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_27", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_27;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_28", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_28;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_29", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_29;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_30", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_30;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_31", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_31;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_32", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_32;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_33", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_33;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_34", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_34;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_35", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_35;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_36", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_36;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_37", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_37;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_38", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_38;
INSERT INTO ipv4_ranges (table_name, min, max) SELECT "ipv4_city_blocks_39", min(network_start_integer), max(network_last_integer) FROM ipv4_city_blocks_39;

VACUUM;